version: '3.8'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    # volumes:
    #   - ./data:/var/lib/mysql
    restart: always
    networks:
      - my_networks
    ports:
      - 3306:3306
  
  web:
    build: ./web

    networks:
      - my_networks

    depends_on:
      - db

networks:
  my_networks: