version: '3.8'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    # volumes:
    #   - ./data:/var/lib/mysql
    restart: always
    networks:
      - my_networks
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        timeout: 5s
        retries: 3
    # ports:
    #   - 3306:3306
  
  web:
    build: ./web
    environment:
      HOST: db
      PORT: 3306
      DB: mydb
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    command: python scripts.py
    networks:
      - my_networks

    depends_on:
      db:
        condition: service_healthy

networks:
  my_networks:
    name: my_networks